### ISSUE TITLE
echo_bot.py ?

### ISSUE THREAD

**Issue by Joan1211** [c17hawke/chatGPT-Telegram-bot#2]
Hello, 
What is the utility of the file **echo_bot.py**

The bot run fine without this file. I have copy/past the 2 files:
**chatgpt.py** and **echo_bot.py** in chatGPT and asked him what is the utility of **echo_bot.py** and it told me that this file is not necessary as everything is already implemented into **chatgpt.py** file.

Can I safely delete echo_bot.py?

**Comment by c17hawke** [comment]
Hi @Joan1211, think of `echo_bot.py` as a hello world program for the `aiogram` telegram bot. It has no other role.
